x=input("enter your name")
print(x)
x=input("enter a number")
print(x)
y=int(x)
print(type(x))
print(type(y))
x=input("enter a float value")
print(x)
y=float(x)
print(type(x))
print(type(y))
x=input("enter a complex number")
print(x)
y=complex(x)
print(type(x))
print(type(y))
